# Video Splitting Settings
clip_duration_minutes: 3
videos_folder: "data/videos/raw"
clips_folder: "data/videos/clips"

# Clip splitting settings (to frames)
frames_per_second: 1
frames_folder: "data/images/frames"

# Processing settings
bbox_padding_factor: 1.10

# Visualization settings
video_out_folder: "out/videos"